version: '3.8'

volumes:
    mongoData4:
        external: true

services:
    mongo:
        image: mongo:4.4
        expose:
            - 27017
        ports:
            - 27017:27017
        environment:
            - TZ=America/Edmonton
        volumes:
            - mongoData4:/data/db

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            - TZ=America/Edmonton
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
